version: '3.3'
services:
  mysql:
    image: mysql:latest
    container_name: image-matcher-container
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d